name: shopping_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  badges: ^2.0.1
  cloud_firestore: ^3.1.0
  cupertino_icons: ^1.0.2
  enum_to_string: ^2.0.1
  firebase_auth: ^3.2.0
  firebase_core: ^1.10.0
  firebase_messaging: ^11.2.1
  flutter:
    sdk: flutter
  flutter_rating_bar: ^4.0.0
  focused_menu: ^1.0.5
  google_fonts: ^2.1.0
  http: ^0.13.4
  intl: ^0.17.0
  provider: ^6.0.1
  shared_preferences: ^2.0.8
  super_tooltip: ^1.0.1

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
